settings:
  enable_draft_pr_reviews: false
  additional_branches_to_be_reviewed:
    - "feature/*"
    - "fix/*"
  disable_high_level_summary: false
  ignored_pr_titles: "WIP"
  review_language: "en"
  disable_review_status: false
  collapse_walkthrough_comment: false
  disable_review: false
  early_access_program: true
  disable_poem: false